  - name: Install apache httpd
    apt:
      name: apache2
      state: latest
      update_cache: yes

  - apache2_module:
      state: present
      name: proxy

  - apache2_module:
      state: present
      name: proxy_http

  - apache2_module:
      state: present
      name: proxy_balancer

  - apache2_module:
      state: present
      name: lbmethod_byrequests
 
  - apache2_module:
      state: present
      name: ssl

  - name: reconfigure default apache site
    blockinfile:
      path: /etc/apache2/sites-available/000-default.conf
      marker: "{mark}"
      marker_begin: "<VirtualHost *:80>"
      marker_end: "</VirtualHost>"
      block: |-
        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/apache.crt
        SSLCertificateKeyFile /etc/apache2/ssl/apache.key
        
        <Proxy balancer://mycluster>
        </Proxy>
          ProxyPreserveHost On
          ProxyPass / balancer://mycluster/
          ProxyPassReverse / balancer://mycluster/
      state: present

  - name: Configure all tomcat servers
    lineinfile:
      path: /etc/apache2/sites-available/000-default.conf
      line: "BalancerMember http://{{ item }}:8080"
      insertafter: <Proxy balancer://mycluster>
      state: present
      create: yes
    loop: "{{ groups['all'] | map('extract',hostvars,['ansible_eth1','ipv4','address']) | list }}"

  - name: remove jenkins from load balancing
    lineinfile:
      path: /etc/apache2/sites-available/000-default.conf
      regexp: 'BalancerMember http://192.168.3.3:8080'
      state: absent

  - name: Create a directory if it does not exist
    file:
      path: /etc/apache2/ssl
      state: directory

  - name: Copy cert
    copy: src={{ item }} dest=/etc/apache2/ssl/
    with_items:
    - apache.crt
    - apache.key

  - name: reload apache2
    systemd:
      state: restarted
      name: apache2

