Description: Create an EC2 instance by AWS CloudFormation
Resources:
  SecurityGroupDemoSvrTraffic:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: Mysec
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: For SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: For HTTP
      GroupDescription: Security Group for server
      VpcId: vpc-0bedc957a18b1f17a
  EC2InstanceDemoSvr:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: us-east-2c
      ImageId: ami-0a63f96e85105c6d3
      InstanceType: t2.micro
      KeyName: first-key
      NetworkInterfaces:
        - Description: Primary network interface
          DeviceIndex: '0'
          SubnetId: subnet-089a84df6157823e8
          PrivateIpAddress: 10.0.0.5
          GroupSet:
            - Ref: SecurityGroupDemoSvrTraffic

      UserData:
        'Fn::Base64':
           !Sub |
              #!/bin/bash
              apt-get update -y
              apt-get install apache2 -y
              service apache2 start
              echo '<!DOCTYPE html><html><head><title>Hello World!</title></head><body><h1>Hello World!</h1></body></html>' > /var/www/html/index.html
      Tags:
        - Key: name
          Value: Myapache2
        - Key: Type
          Value: MyHelloWorld

