---
- hosts: 192.168.3.2
  become: yes
  become_method: sudo
  tasks:
  - name: remove first tomcat from balancing
    lineinfile:
      path: /etc/apache2/sites-available/000-default.conf
      regexp: 'BalancerMember http://192.168.3.4:8080'
      line: "#BalancerMember http://192.168.3.4:8080"
      state: present

- hosts: 192.168.3.4
  become: yes
  become_method: sudo
  tasks:
  - name: download gradle app on tomcat1
    get_url:
      url: "http://192.168.3.3:8081/nexus/content/repositories/releases/admin/gradleapp/{{ lookup('file', 'gradle.properties') | replace('version = ', '') }}/gradleapp-{{ lookup('file', 'gradle.properties') | replace('version = ', '') }}.war"
      dest: /usr/share/tomcat/apache-tomcat-9.0.34/webapps/myapp.war
      force: yes

- hosts: 192.168.3.2
  become: yes
  become_method: sudo
  tasks:
  - name: add first tomcat to balancer
    lineinfile:
      path: /etc/apache2/sites-available/000-default.conf
      regexp: '#BalancerMember http://192.168.3.4:8080'
      line: BalancerMember http://192.168.3.4:8080
      state: present

- hosts: 192.168.3.2
  become: yes
  become_method: sudo
  tasks:
  - name: remove second tomcat from balancing
    lineinfile:
      path: /etc/apache2/sites-available/000-default.conf
      regexp: 'BalancerMember http://192.168.3.5:8080'
      line: "#BalancerMember http://192.168.3.5:8080"
      state: present

- hosts: 192.168.3.5
  become: yes
  become_method: sudo
  tasks:
  - name: download gradle app on tomcat2
    get_url:
      url: "http://192.168.3.3:8081/nexus/content/repositories/releases/admin/gradleapp/{{ lookup('file', 'gradle.properties') | replace('version = ', '') }}/gradleapp-{{ lookup('file', 'gradle.properties') | replace('version = ', '') }}.war"
      dest: /usr/share/tomcat/apache-tomcat-9.0.34/webapps/myapp.war
      force: yes

- hosts: 192.168.3.2
  become: yes
  become_method: sudo
  tasks:
  - name: add first tomcat to balancer
    lineinfile:
      path: /etc/apache2/sites-available/000-default.conf
      regexp: '#BalancerMember http://192.168.3.5:8080'
      line: BalancerMember http://192.168.3.5:8080
      state: present

  - debug:
      msg: "Application version is {{ lookup('file', 'gradle.properties') | replace('version = ', '') }}"
