---
     - name: Install JDK
       apt:
         name: openjdk-8-jdk
         state: latest
         update_cache: yes

     - name: Install git
       apt:
         name: git
         state: latest
         update_cache: yes

     - name: Import Jenkins Key
       apt_key:
         url: https://pkg.jenkins.io/debian/jenkins.io.key
         state: present
       retries: 3
       delay: 3
       register: result
       until: result is succeeded

     - name: Adding jenkins PUB key
       command:
         cmd: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9B7D32F2D50582E6

     - apt_repository :
         repo: 'deb http://pkg.jenkins.io/debian-stable binary/'

     - name: Install Jenkins
       apt:
         name: jenkins
         state: latest
         update_cache: yes

     - name: Start Jenkins
       systemd:
         name: jenkins
         state: started
         enabled: true

     - git:
         repo: https://github.com/Jcodex/dockertask.git
         dest: /home/mygit
         version: task5


     - name: Create initialization scripts directory
       file: path=/var/lib/jenkins/init.groovy.d
         state=directory
         owner=jenkins
         group=jenkins
         mode=0775

     - name: Skipping manual jenkins installation and allowing ansible jenkins plugin module download plugins
       lineinfile:
         path: /etc/default/jenkins
         regexp: ^JAVA_ARGS=
         line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false $JAVA_ARGS -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true"'
         become: true

     - name: Copy groovy script
       command:
         cmd: cp -r /home/mygit/security.groovy /var/lib/jenkins/init.groovy.d
         cmd: cp -r /home/mygit/user.groovy /var/lib/jenkins/init.groovy.d
 
     - name: Restart jenkins server
       service:
         name: jenkins
         state: restarted

     - name: wait for jenkins service
       wait_for:
         timeout: 10
         delegate_to: localhost

     - name: remove used groovy scripts
       command:
         cmd: rm -r /var/lib/jenkins/init.groovy.d        


