---
- hosts: all, !server1, !server2
  become: yes
  become_method: sudo
  tasks:
  - name: Install JDK
    apt:
      name: default-jdk
      state: latest
      update_cache: yes

  - name: Ensure group "tomcat" exists
    group:
      name: tomcat
      state: present

  - name: Add the user 'tomcat'
    user:
      name: tomcat
      comment: tomtom
      uid: 1040
      group: tomcat

  - name: Download tomcat
    get_url:
      url: http://www-eu.apache.org/dist/tomcat/tomcat-9/v9.0.34/bin/apache-tomcat-9.0.34.tar.gz
      dest: /tmp

  - name: Create a directory if it does not exist
    file:
      path: /usr/share/tomcat
      state: directory

  - name: Extract apache
    unarchive:
      src: /tmp/apache-tomcat-9.0.34.tar.gz
      dest: /usr/share/tomcat
      remote_src: yes
      creates: /usr/share/tomcat/apache-tomcat-9.0.34

  - name: Change file ownership, group and permissions
    file:
      path: /usr/share/tomcat
      owner: tomcat
      group: tomcat
      recurse: yes

  - name: configure tomcat
    blockinfile:
      path: /etc/systemd/system/tomcat.service
      create: yes
      block: |
        [Unit]
        Description=Tomcat 9 servlet container
        After=network.target
        [Service]
        Type=forking
        User=tomcat
        Group=tomcat
        Environment="JAVA_HOME=/usr/lib/jvm/default-java"
        Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom -Djava.awt.headless=true"
        Environment="CATALINA_BASE=/usr/share/tomcat/apache-tomcat-9.0.34"
        Environment="CATALINA_HOME=/usr/share/tomcat/apache-tomcat-9.0.34"
        Environment="CATALINA_PID=/usr/share/tomcat/apache-tomcat-9.0.34/temp/tomcat.pid"
        Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
        ExecStart=/usr/share/tomcat/apache-tomcat-9.0.34/bin/startup.sh
        ExecStop=/opt/tomcat/apache-tomcat-9.0.34/bin/shutdown.sh
        [Install]
        WantedBy=multi-user.target
  
  - name: Create a directory for index.html
    file:
      path: /usr/share/tomcat/webapps/www/
      state: directory
      recurse: yes

  - name: create index.html
    blockinfile:
      path: /usr/share/tomcat/apache-tomcat-9.0.34/webapps/www/index.html
      create: yes
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      block: |
        <!DOCTYPE html>
        <html>
           <head>
             <title>TestTestTest</title>
           </head>
           <body>
             <p>HelloWorld</p>
           </body>
        </html>
  - name: start tomcat                 
    systemd:
      daemon_reload: yes
      state: started
      name: tomcat

  - name: enable tomcat                 
    service:
      enabled: yes
      name: tomcat

  - name: Allow all access to tcp port 8080
    ufw:
      rule: allow
      port: '8080'
      proto: tcp

  - name: create tomcat user
    blockinfile:
      path: /usr/share/tomcat/apache-tomcat-9.0.34/conf/tomcat-users.xml
      create: yes
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      insertbefore: </tomcat-users>
      block: |
        <role rolename="admin-gui"/>
        <role rolename="manager-gui"/>
        <user username="admin" password="admin" roles="admin-gui,manager-gui"/>
 
  - name: Allow tomcat connection from host
    lineinfile:
      path: /usr/share/tomcat/apache-tomcat-9.0.34/webapps/manager/META-INF/context.xml
      regexp: 'allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1" />'
      line: 'allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1|192.168.3.1|192.168.3.2" />'

  - name: Allow tomcat connection from host      
    lineinfile:
      path: /usr/share/tomcat/apache-tomcat-9.0.34/webapps/host-manager/META-INF/context.xml
      regexp: 'allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1" />'
      line: 'allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1|192.168.3.1|192.168.3.2" />'

  - name: restart tomcat
    systemd:
      name: tomcat
      state: restarted


############################################################# Install Jenkins


- hosts: server2
  become: yes
  become_method: sudo
  tasks:
     - name: Install JDK
       apt:
         name: openjdk-8-jdk
         state: latest
         update_cache: yes

     - name: Install git
       apt:
         name: git
         state: latest
         update_cache: yes

     - name: Import Jenkins Key
       apt_key:
         url: https://pkg.jenkins.io/debian/jenkins.io.key
         state: present
       retries: 3
       delay: 3
       register: result
       until: result is succeeded

     - name: Adding jenkins PUB key
       command:
         cmd: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9B7D32F2D50582E6

     - apt_repository :
         repo: 'deb http://pkg.jenkins.io/debian-stable binary/'

     - name: Install Jenkins
       apt:
         name: jenkins
         state: latest
         update_cache: yes

     - name: Start Jenkins
       systemd:
         name: jenkins
         state: started
         enabled: true

     - git:
         repo: https://github.com/Jcodex/devops.git
         dest: /home/mygit
         version: task5

     - name: Create initialization scripts directory
       file: path=/var/lib/jenkins/init.groovy.d
         state=directory
         owner=jenkins
         group=jenkins
         mode=0775

     - name: Skipping manual jenkins installation and allowing ansible jenkins plugin module download plugins
       lineinfile:
         path: /etc/default/jenkins
         regexp: ^JAVA_ARGS=
         line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false $JAVA_ARGS -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true"'

     - name: Copy groovy script
       command:
         cmd: cp -r /home/mygit/security.groovy /var/lib/jenkins/init.groovy.d
         cmd: cp -r /home/mygit/user.groovy /var/lib/jenkins/init.groovy.d
 
     - name: Restart jenkins server
       service:
         name: jenkins
         state: restarted

     - name: wait for jenkins service
       uri:
         url: "http://192.168.3.3:8080/login"
         status_code: 200
       register: login_page
       until: login_page.status == 200
       retries: 60
       delay: 5

     - name: remove used groovy scripts
       command:
         cmd: rm -r /var/lib/jenkins/init.groovy.d        

     - name: Allowing jenkins run commands as root
       lineinfile:
         path: /etc/sudoers
         line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
       become: true

     - name: Restart jenkins
       service:
         name: jenkins
         state: restarted

     - name: Wait untill jenkins apply changes
       uri:
         url: "http://192.168.3.3:8080/login"
         status_code: 200
       register: login_page
       until: login_page.status == 200
       retries: 60
       delay: 5

     - name: Download git plugin
       jenkins_plugin:
         name: git
         url_username: admin
         url_password: admin
         url: http://192.168.3.3:8080
       retries: 3
       delay: 5
       register: result
       until: result is succeeded

     - name: Download pipeline plugin
       jenkins_plugin:
         name: workflow-aggregator
         url_username: admin
         url_password: admin
         url: http://192.168.3.3:8080
       retries: 3
       delay: 5
       register: result
       until: result is succeeded

     - name: Install python pip
       package:
         name: python-pip
         state: present
         update_cache: yes

     - name: Install python lxml
       package:
         name:  python3-lxml
         state: present
         update_cache: yes

     - pip:
         name: python-jenkins

     - pip:
         name: lxml

     - name: Restart jenkins
       service:
         name: jenkins
         state: restarted

     - name: wait for jenkins service
       uri:
         url: "http://192.168.3.3:8080/login"
         status_code: 200
       register: login_page
       until: login_page.status == 200
       retries: 60
       delay: 5

     - jenkins_job:
         config: "{{ lookup('file', 'gradlepipe.xml') }}"
         name: pipe
         password: admin
         url: http://192.168.3.3:8080
         user: admin


     - name: Restart jenkins
       service:
         name: jenkins
         state: restarted

     - name: Download nexus
       get_url:
         url: http://www.sonatype.org/downloads/nexus-latest-bundle.zip
         dest: /opt
    
     - name: Install zip
       apt:
         name: zip
         state: present

     - name: Unarchive nexus
       unarchive:
         src: /opt/nexus-2.14.18-01-bundle.zip
         dest: /opt
         remote_src: yes

     - name: Create user for nexus
       user:
         name: nexus

     - name: Allow nexus start without password
       lineinfile:
         path: /etc/sudoers
         line: 'nexus ALL=(ALL) NOPASSWD: ALL'
       become: true

     - name: Change nexus ownership
       file:
         path: /opt/nexus-2.14.18-01
         owner: nexus
         recurse: yes

     - name: Change nexus ownership
       file:
         path: /opt/sonatype-work
         owner: nexus
         recurse: yes

     - name: Configure nexus to run as custom user
       lineinfile:
         path: /opt/nexus-2.14.18-01/bin/nexus
         line: 'RUN_AS_USER=nexus'
         regexp: '#RUN_AS_USER='
         create: yes

     - file:
        src: /opt/nexus-2.14.18-01/bin/nexus
        dest: /etc/init.d/nexus
        state: link

     - name: force systemd to reread configs
       systemd:
         daemon_reload: yes

     - name: start nexus
       systemd:
         state: started
         name: nexus
    

#################################################### Install apache

- hosts: server1
  become: yes
  become_method: sudo
  tasks:

  - name: Install apache httpd
    apt:
      name: apache2
      state: latest
      update_cache: yes

  - apache2_module:
      state: present
      name: proxy

  - apache2_module:
      state: present
      name: proxy_http

  - apache2_module:
      state: present
      name: proxy_balancer

  - apache2_module:
      state: present
      name: lbmethod_byrequests
 
  - apache2_module:
      state: present
      name: ssl

  - name: reconfigure default apache site
    blockinfile:
      path: /etc/apache2/sites-available/000-default.conf
      marker: "{mark}"
      marker_begin: "<VirtualHost *:80>"
      marker_end: "</VirtualHost>"
      block: |-
        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/apache.crt
        SSLCertificateKeyFile /etc/apache2/ssl/apache.key
        
        <Proxy balancer://mycluster>
        </Proxy>
          ProxyPreserveHost On
          ProxyPass / balancer://mycluster/
          ProxyPassReverse / balancer://mycluster/
      state: present

  - name: Configure all tomcat servers
    lineinfile:
      path: /etc/apache2/sites-available/000-default.conf
      line: "BalancerMember http://{{ item }}:8080"
      insertafter: <Proxy balancer://mycluster>
      state: present
      create: yes
    loop: "{{ groups['all'] | map('extract',hostvars,['ansible_eth1','ipv4','address']) | list }}"

  - name: remove jenkins from load balancing
    lineinfile:
      path: /etc/apache2/sites-available/000-default.conf
      regexp: 'BalancerMember http://192.168.3.3:8080'
      state: absent

  - name: Create a directory if it does not exist
    file:
      path: /etc/apache2/ssl
      state: directory

  - name: Copy cert
    copy: src={{ item }} dest=/etc/apache2/ssl/
    with_items:
    - apache.crt
    - apache.key

  - name: reload apache2
    systemd:
      state: restarted
      name: apache2

  - name: Queue build of a project in Jenkins
    uri:
      url: http://192.168.3.3:8080/job/pipe/build?token=build_me
      user: "admin"
      password: "admin"
      method: GET
      force_basic_auth: yes
      status_code: 201

  - name: wait for webapp appearing in nexus
    uri:
      url: "http://192.168.3.3:8081/nexus/content/repositories/releases/admin/gradleapp/1.0.1/gradleapp-1.0.1.war"
      status_code: 200
    register: result
    until: result.status == 200
    retries: 60
    delay: 5

- hosts: server3
  become: yes
  become_method: sudo
  tasks:
    
  - name: change content of 1 of tomcat servers
    lineinfile:
      path: /usr/share/tomcat/apache-tomcat-9.0.34/webapps/www/index.html
      regexp: ^<p>HelloWorld</p>
      line: HelloWorld2

- hosts: all, !server1, !server2
  become: yes
  become_method: sudo
  tasks:

  - name: download gradle app
    get_url:
      url: http://192.168.3.3:8081/nexus/content/repositories/releases/admin/gradleapp/1.0.1/gradleapp-1.0.1.war
      dest: /usr/share/tomcat/apache-tomcat-9.0.34/webapps
