---
- hosts: all
  become: yes
  become_method: sudo
  tasks: 
  - debug:
      msg: establish ssh connection between nodes
  
  - name: Copy pubkey
    copy:
      src: id_rsa.pub
      dest: /home/vagrant/.ssh
      owner: vagrant
      mode: '700'

  - name: Copy private key
    copy:
      src: id_rsa
      dest: /home/vagrant/.ssh
      owner: vagrant
      mode: '600'

  - name: update authorized_keys
    lineinfile:
      path: /home/vagrant/.ssh/authorized_keys
      line: "{{ lookup('file', 'id_rsa.pub') }}"
      state: present

- hosts: all, !server1, !server2
  become: yes
  become_method: sudo
  roles:
    - tomcat

- hosts: server1
  become: yes
  become_method: sudo
  roles:
   - https_apache

- hosts: server2
  become: yes
  become_method: sudo
  roles:
    - jenkins_nexus
