  - name: Install JDK
    apt:
      name: default-jdk
      state: latest
      update_cache: yes

  - name: Ensure group "tomcat" exists
    group:
      name: tomcat
      state: present

  - name: Add the user 'tomcat'
    user:
      name: tomcat
      comment: tomtom
      uid: 1040
      group: tomcat

  - name: Download tomcat
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.35/bin/apache-tomcat-9.0.35.tar.gz
      dest: /tmp

  - name: Create a directory if it does not exist
    file:
      path: /usr/share/tomcat
      state: directory

  - name: Extract apache
    unarchive:
      src: /tmp/apache-tomcat-9.0.35.tar.gz
      dest: /usr/share/tomcat
      remote_src: yes
      creates: /usr/share/tomcat/apache-tomcat-9.0.35

  - name: Change file ownership, group and permissions
    file:
      path: /usr/share/tomcat
      owner: tomcat
      group: tomcat
      recurse: yes

  - name: configure tomcat
    blockinfile:
      path: /etc/systemd/system/tomcat.service
      create: yes
      block: |
        [Unit]
        Description=Tomcat 9 servlet container
        After=network.target
        [Service]
        Type=forking
        User=tomcat
        Group=tomcat
        Environment="JAVA_HOME=/usr/lib/jvm/default-java"
        Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom -Djava.awt.headless=true"
        Environment="CATALINA_BASE=/usr/share/tomcat/apache-tomcat-9.0.35"
        Environment="CATALINA_HOME=/usr/share/tomcat/apache-tomcat-9.0.35"
        Environment="CATALINA_PID=/usr/share/tomcat/apache-tomcat-9.0.35/temp/tomcat.pid"
        Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
        ExecStart=/usr/share/tomcat/apache-tomcat-9.0.35/bin/startup.sh
        ExecStop=/opt/tomcat/apache-tomcat-9.0.35/bin/shutdown.sh
        [Install]
        WantedBy=multi-user.target
  
  - name: Create a directory for index.html
    file:
      path: /usr/share/tomcat/webapps/www/
      state: directory
      recurse: yes

  - name: create index.html
    blockinfile:
      path: /usr/share/tomcat/apache-tomcat-9.0.35/webapps/www/index.html
      create: yes
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      block: |
        <!DOCTYPE html>
        <html>
           <head>
             <title>TestTestTest</title>
           </head>
           <body>
             <p>HelloWorld</p>
           </body>
        </html>
  - name: start tomcat                 
    systemd:
      daemon_reload: yes
      state: started
      name: tomcat

  - name: enable tomcat                 
    service:
      enabled: yes
      name: tomcat

  - name: Allow all access to tcp port 8080
    ufw:
      rule: allow
      port: '8080'
      proto: tcp

  - name: create tomcat user
    blockinfile:
      path: /usr/share/tomcat/apache-tomcat-9.0.35/conf/tomcat-users.xml
      create: yes
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      insertbefore: </tomcat-users>
      block: |
        <role rolename="admin-gui"/>
        <role rolename="manager-gui"/>
        <user username="admin" password="admin" roles="admin-gui,manager-gui"/>
 
  - name: Allow tomcat connection from host
    lineinfile:
      path: /usr/share/tomcat/apache-tomcat-9.0.35/webapps/manager/META-INF/context.xml
      regexp: 'allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1" />'
      line: 'allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1|192.168.3.1|192.168.3.2" />'

  - name: Allow tomcat connection from host      
    lineinfile:
      path: /usr/share/tomcat/apache-tomcat-9.0.35/webapps/host-manager/META-INF/context.xml
      regexp: 'allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1" />'
      line: 'allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1|192.168.3.1|192.168.3.2" />'

  - name: restart tomcat
    systemd:
      name: tomcat
      state: restarted


