  - name: Install JDK
    apt:
      name: openjdk-8-jdk
      state: latest
      update_cache: yes

  - name: Install git
    apt:
      name: git
      state: latest
      update_cache: yes

  - name: Install ansible
    apt:
      name: ansible
      state: latest
      update_cache: yes

  - name: Add ansible hosts
    lineinfile:
      path: /etc/ansible/hosts
      line: "{{ item }}"
      state: present
      create: yes
    loop: "{{ groups['all'] | map('extract',hostvars,['ansible_eth1','ipv4','address']) | list }}"

  - name: Recursively change ownership of a directory
    file:
      path: /home/vagrant/.ansible
      state: directory
      recurse: yes
      owner: vagrant

  - name: Import Jenkins Key
    apt_key:
      url: https://pkg.jenkins.io/debian/jenkins.io.key
      state: present
    retries: 3
    delay: 3
    register: result
    until: result is succeeded

  - name: Adding jenkins PUB key
    command:
      cmd: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9B7D32F2D50582E6

  - apt_repository :
      repo: 'deb http://pkg.jenkins.io/debian-stable binary/'

  - name: Install Jenkins
    apt:
      name: jenkins
      state: latest
      update_cache: yes

  - name: Start Jenkins
    systemd:
      name: jenkins
      state: started
      enabled: true

  - git:
      repo: https://github.com/Jcodex/devops.git
      dest: /home/mygit
      version: task5

  - name: Create initialization scripts directory 
    file: path=/var/lib/jenkins/init.groovy.d
      state=directory
      owner=jenkins
      group=jenkins
      mode=0775

  - name: Skipping manual jenkins installation and allowing ansible jenkins plugin module download plugins
    lineinfile:
      path: /etc/default/jenkins
      regexp: ^JAVA_ARGS=
      line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false $JAVA_ARGS -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true"'

  - name: Copy groovy script
    command:
      cmd: cp -r /home/mygit/security.groovy /var/lib/jenkins/init.groovy.d
      cmd: cp -r /home/mygit/user.groovy /var/lib/jenkins/init.groovy.d
 
  - name: Restart jenkins server
    service:
      name: jenkins
      state: restarted

  - name: wait for jenkins service
    uri:
      url: "http://192.168.3.3:8080/login"
      status_code: 200
    register: login_page
    until: login_page.status == 200
    retries: 60
    delay: 5

  - name: remove used groovy scripts
    command:
      cmd: rm -r /var/lib/jenkins/init.groovy.d        

  - name: Allowing jenkins run commands as root
    lineinfile:
      path: /etc/sudoers
      line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
    become: true

  - name: Restart jenkins
    service:
      name: jenkins
      state: restarted

  - name: Wait untill jenkins apply changes
    uri:
      url: "http://192.168.3.3:8080/login"
      status_code: 200
    register: login_page
    until: login_page.status == 200
    retries: 60
    delay: 5

  - name: Install python pip
    package:
      name: python-pip
      state: present
      update_cache: yes

  - name: Install python lxml
    package:
      name:  python3-lxml
      state: present
      update_cache: yes

  - pip:
      name: python-jenkins

  - pip:
      name: lxml

  - name: Restart jenkins
    service:
      name: jenkins
      state: restarted
