  - name: Download nexus
    get_url:
      url: http://www.sonatype.org/downloads/nexus-latest-bundle.zip
      dest: /opt
    
  - name: Install zip
    apt:
      name: zip
      state: present

  - name: Unarchive nexus
    unarchive:
      src: /opt/nexus-2.14.18-01-bundle.zip
      dest: /opt
      remote_src: yes

  - name: Create user for nexus
    user:
      name: nexus

  - name: Allow nexus start without password
    lineinfile:
      path: /etc/sudoers
      line: 'nexus ALL=(ALL) NOPASSWD: ALL'
    become: true

  - name: Change nexus ownership
    file:
      path: /opt/nexus-2.14.18-01
      owner: nexus
      recurse: yes

  - name: Change nexus ownership
    file:
      path: /opt/sonatype-work
      owner: nexus
      recurse: yes

  - name: Configure nexus to run as custom user
    lineinfile:
      path: /opt/nexus-2.14.18-01/bin/nexus
      line: 'RUN_AS_USER=nexus'
      regexp: '#RUN_AS_USER='
      create: yes

  - file:
      src: /opt/nexus-2.14.18-01/bin/nexus
      dest: /etc/init.d/nexus
      state: link

  - name: force systemd to reread configs
    systemd:
      daemon_reload: yes

  - name: start nexus
    systemd:
      state: started
      name: nexus
    

